kind: pipeline
type: docker
name: test001

platform:
  os: linux
  arch: amd64

steps:
- name: Test output
  image: debian:stable
  commands:
  - echo -e 'hello world'
  - cat /drone/src/.git/first.txt